networks:
  net:
    driver: bridge

services:
  hortonworks_host:
    image: hortonworks/sandbox-hdp:3.0.1
    container_name: "hortonworks_host"
    hostname: "sandbox-hdp.hortonworks.com"
    privileged: true
    networks:
      - net
    ports:
      - 2222:22
      - 8080:8080
      - 1080:1080
      - 21000:21000
      - 6080:6080
      - 50070:50070
      - 9995:9995
      - 30800:30800
      - 4200:4200
      - 8088:8088
      - 19888:19888
      - 16010:16010
      - 11000:11000
      - 8744:8744
      - 8886:8886
      - 18081:18081
      - 8443:8443
      - 10000:10000
