networks:
  net:
    driver: bridge

services:
  nifi:
    image: apache/nifi:latest
    restart: unless-stopped
    container_name: "nifi"
    hostname: "nifi"
    environment:
      NIFI_WEB_HTTP_PORT: 8443
    depends_on:
      minio:
        condition: service_healthy
    networks:
      - net
    ports:
      - "8443:8443"
      - "8081:8081"
